version: '3.8'
services:
  alticci-service:
    depends_on:
      - redis-service
    image: 'ghcr.io/eduaugustoo/alticci-service:latest'
    container_name: alticci-service
    ports: 
      - 8080:8080
    environment:
      - SPRING_REDIS_HOST=redis-service
    networks:
      backend:
        aliases:
          - 'alticci-service'

  redis-service:
    image: 'redis:7.0'
    container_name: 'redis-service'
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - 'redis-service'

networks:
  backend:
    driver: bridge